table _Measures
	lineageTag: b70fb10b-87cc-4cf9-9c8c-614fb0669d5c

	measure TotalEmployees = COUNTA(DimEmployee[EmployeeID])
		formatString: 0
		lineageTag: 9ba849b6-f9d0-41e2-8c1c-49d43357d0c3

	measure ActiveEmployees = CALCULATE(COUNT(DimEmployee[Attrition]),DimEmployee[Attrition]="No")
		formatString: 0
		lineageTag: 1c570435-f2c9-486a-8cad-d7692587ed0c

	measure InactiveEmployees = CALCULATE(COUNT(DimEmployee[Attrition]),DimEmployee[Attrition]="Yes")
		formatString: 0
		lineageTag: 6e9bf5cc-892c-4157-a18e-a31f7ad2be5e

	measure '% Attrition Rate' = [InactiveEmployees]/[TotalEmployees]
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 2092ae71-3b2b-413b-b8c4-d31d1688d573

	measure TotalEmployeesDate = CALCULATE([TotalEmployees],USERELATIONSHIP(DimEmployee[HireDate], DimDate[Date]))
		formatString: 0
		lineageTag: 726bdc05-9797-4b34-a2a6-dd3f5d9eeb61

	measure 'Youngest Employee' = min(DimEmployee[Age])
		formatString: 0
		lineageTag: fca37c94-6c2b-4e9a-ab31-79eb022118d4

	measure 'Oldest Employee' = max(DimEmployee[Age])
		formatString: 0
		lineageTag: d94b3a35-949d-444e-af28-242b79353423

	measure AverageSalary = AVERAGE(DimEmployee[Salary])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9b9d1c4d-25e2-41c8-9d94-5e33594ae995

	measure LastReviewDate =
			IF (
			    MAX ( FactPerformanceRating[ReviewDate] ) = BLANK (),
			    "No Review Yet",
			    FORMAT(MAX ( FactPerformanceRating[ReviewDate] ), "mm/dd/yyyy" ))
		lineageTag: 35ca1aac-6f36-4e10-ad2c-248da6237628

	measure NextReviewDate = ```
			
						VAR LastReview = MAX ( FactPerformanceRating[ReviewDate] )
						VAR HireDate = MAX ( DimEmployee[HireDate] )
						RETURN
							IF (
								NOT ISBLANK ( LastReview ),
								FORMAT ( LastReview + 365, "MM/dd/yyyy" ),
								FORMAT ( HireDate + 365, "MM/dd/yyyy" )
							)
			```
		lineageTag: e82ecf63-ed75-488b-be36-e1bef9101672

	measure JobSatisfaction = MAX(FactPerformanceRating[JobSatisfaction])
		formatString: 0
		lineageTag: 86661fba-5998-480c-9a20-56c63db4b6b2

	measure EnvironmentSatisfaction = CALCULATE(MAX(FactPerformanceRating[EnvironmentSatisfaction]), USERELATIONSHIP(FactPerformanceRating[EnvironmentSatisfaction], DimSatisfiedLevel[SatisfactionID]))
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	measure RelationshipSatisfaction = CALCULATE(MAX(FactPerformanceRating[RelationshipSatisfaction]), USERELATIONSHIP(FactPerformanceRating[RelationshipSatisfaction], DimSatisfiedLevel[SatisfactionID]))
		lineageTag: b2c3d4e5-f6g7-8901-bcde-f23456789012

	measure WorkLifeBalance = CALCULATE(MAX(FactPerformanceRating[WorkLifeBalance]), USERELATIONSHIP(FactPerformanceRating[WorkLifeBalance], DimSatisfiedLevel[SatisfactionID]))
		lineageTag: c3d4e5f6-g7h8-9012-cdef-345678901234

	column Column
		formatString: 0
		lineageTag: 21e298f0-3dfb-474d-bcde-082c73fd4470
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 52cf6400594b403ba84dfc3ae3f28746

