table DimRatingLevel
	lineageTag: 3c10fa1c-d6f8-4ed3-bf03-1bd59f676d7b

	column RatingID
		dataType: int64
		formatString: 0
		lineageTag: 6ae5a375-3c2c-436c-a645-3ea1af5d834e
		summarizeBy: none
		sourceColumn: RatingID

		annotation SummarizationSetBy = Automatic

	column RatingLevel
		dataType: string
		lineageTag: 9a1f031d-dc14-4dc4-95ca-c4a7bb8996ae
		summarizeBy: none
		sourceColumn: RatingLevel

		annotation SummarizationSetBy = Automatic

	partition DimRatingLevel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tulio\Documents\Power BI Desktop\case-study-hr-analytics-in-power-bi\Datasets\RatingLevel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RatingID", Int64.Type}, {"RatingLevel", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

