table DimSatisfiedLevel
	lineageTag: 522d4a8d-e96b-4184-9876-5d0809f0a7ab

	column SatisfactionID
		dataType: int64
		formatString: 0
		lineageTag: 699bf277-c9cc-4f1c-be60-85dbe59a4f1b
		summarizeBy: none
		sourceColumn: SatisfactionID

		annotation SummarizationSetBy = Automatic

	column SatisfactionLevel
		dataType: string
		lineageTag: f0ea367f-1b04-4295-a3e0-0131952a4150
		summarizeBy: none
		sourceColumn: SatisfactionLevel

		annotation SummarizationSetBy = Automatic

	partition DimSatisfiedLevel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tulio\Documents\Power BI Desktop\case-study-hr-analytics-in-power-bi\Datasets\SatisfiedLevel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SatisfactionID", Int64.Type}, {"SatisfactionLevel", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

